kind: Deployment
apiVersion: apps/v1
metadata:
  name: symfony-demo
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: symfony-demo
  template:
    metadata:
       labels:
          app: symfony-demo
    spec:
      containers:
        - name: symfony-demo
          image: bashofmann/symfony-demo:2.0.6
          livenessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 80
            timeoutSeconds: 1
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: symfony-demo
spec:
  ports:
  -
    name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: symfony-demo
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: symfony-demo
  annotations:
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - symfony-demo.bastian.plgrnd.be
    secretName: symfony-demo-secret
  rules:
  - host: symfony-demo.bastian.plgrnd.be
    http:
      paths:
      - path: /
        backend:
          serviceName: symfony-demo
          servicePort: 80
